### ISSUE TITLE
Foldable markers in customize buffers are almost invisible

### ISSUE THREAD

**Issue by andreyorst** [doomemacs/themes#645]
## What happened?
Here's how triangle buttons look with `doom-one-light`:

![image](https://user-images.githubusercontent.com/19470159/127902158-55b25158-2f2b-44a0-ab13-3a4e402609c6.png)

And with `doom-one`:

![image](https://user-images.githubusercontent.com/19470159/127902065-a26fdbf3-77f2-48ff-b457-7768711085f2.png)

Also happens in `doom-dracula`, `doom-gruvbox`, `doom-henna`, `doom-spacegrey`, and almost all other dark themes.

I suspect that this is due to most of those having shadow face way to close to the background:

![image](https://user-images.githubusercontent.com/19470159/127902531-70389900-b7c6-4e0a-9cb6-a0cca57ca614.png)

But I'm not sure, as I can't find what face this button uses.

## Steps to reproduce
1. enable doom-one
2. open customize

## System Information
+ Emacs version: 28.0.50
+ Emacs distro:  None
+ Operating system: Fedora 34 
+ Installed commit of doom-themes:20f9eb93a28817eb39b39899022c2971e015e49d 
+ Which theme are you using: doom-spacegrey

**Comment by hlissner** [comment]
Was this a false positive or fixed?
