### ISSUE TITLE
ansi-color-names-vector is obsolete in emacs 28

### ISSUE THREAD

**Issue by memeplex** [doomemacs/themes#674]
### What did you expect to happen?

shell mode to change color accordingly to current theme.

### What actually happened?

Even though doom themes changes ansi-color-names-vector, shell colors stay the same.

The docstring for ansi-color-names-vector states:

> This variable is obsolete.  To customize the display of colors used by
ansi-color, change ’ansi-color-COLOR’, e.g. ‘ansi-color-red’.  To
customize the actual faces used (e.g. to temporarily display SGR
control sequences differently), use ‘ansi-color-normal-colors-vector’.

### Describe your attempts to resolve the issue

It shouldn't be difficult to take the current vector and set foreground colors for the new faces from it. I'll give it a try tomorrow.

### Steps to reproduce

1. M-x shell
2. Change themes

(emacs 28)

### Package commit

e716ddbb882a3a06744faa74decb2fea1569c921

### System Information

macOS Big Sur, emacs-28 branch.

**Comment by WhatDothLife** [comment]
We also need these:

```
(custom-set-faces
 `(ansi-color-bright-black ((t (:foreground ,(doom-color 'bg)))))
 `(ansi-color-bright-red ((t (:foreground ,(doom-color 'red)))))
 `(ansi-color-bright-green ((t (:foreground ,(doom-color 'green)))))
 `(ansi-color-bright-yellow ((t (:foreground ,(doom-color 'yellow)))))
 `(ansi-color-bright-blue ((t (:foreground ,(doom-color 'blue)))))
 `(ansi-color-bright-magenta ((t (:foreground ,(doom-color 'magenta)))))
 `(ansi-color-bright-cyan ((t (:foreground ,(doom-color 'cyan))))))
```

**Comment by hlissner** [comment]
Sorry for the late response! This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
