### ISSUE TITLE
Ugly emacs 28 bookmark fringe indicator

### ISSUE THREAD

**Issue by memeplex** [doomemacs/themes#677]
### What did you expect to happen?

Properly themed bookmark fringe indicator.

### What actually happened?

Many themes show a poorly colorized fringe indicator:

![image](https://user-images.githubusercontent.com/2845433/137600837-98a828a9-ba05-468c-9e89-b25a00eee5c2.png)

![image](https://user-images.githubusercontent.com/2845433/137600854-0e1e43d5-c032-4d5f-ae6c-b95221ab23cb.png)

I assume this is because it's a recently developed feature that isn't still properly supported by doom themes.

### Steps to reproduce

1. Ensure `bookmark-set-fringe-mark` is `t` (should be so by default)
2. Load some theme, for example `doom-solarized-dark`
3. Open a file, say `/tmp/test.txt`
4. Write some text and set a bookmark with `C-x r m`
5. Look at the mark in the left fringe.

### Package commit

e716ddbb882a3a06744faa74decb2fea1569c921

**Comment by elfehr** [comment]
In case anybody else updates emacs, suddenly wonder what those dots are, and ends up here: they are themed by bookmark-face, so it should be easy to remove the background, for example I did that:

``` elisp
(use-package bookmark
  :custom-face (bookmark-face ((t (:background nil)))))
```
