### ISSUE TITLE
Treemacs theme shows non-doom icons for certain files (with a certain config)

### ISSUE THREAD

**Issue by bk138** [doomemacs/themes#688]
### What did you expect to happen?

Treemacs showing doom icons for Cargo.lock files, like this:
![Bildschirmfoto von 2021-12-10 13-19-27](https://user-images.githubusercontent.com/80450/145573223-4bf0c31a-c94c-40c7-8ec2-bbcecf8c3f8f.png)

### What actually happened?

Treemacs shows some doom icons, but for certain files (Cargo.lock, Cargo.toml, also systemd unit files, probably more) it shows the PNG icon shipped with treemacs, which is way bigger and out of indent order:
![Bildschirmfoto von 2021-12-10 13-21-06](https://user-images.githubusercontent.com/80450/145573461-6f15132e-90e9-4466-889c-36f3ccdc3654.png)

### Describe your attempts to resolve the issue

I tried with use-package's `after:` but to no avail. I then tried to minimise [my emacs config which exposes the issue](https://github.com/bk138/dotfiles/blob/master/.emacs) to a minimal example that triggers the bug, see next section.

### Steps to reproduce

1. `rm -rf ~/.emacs.d/elpa/` # start with a clean state
2. use [this init file](https://pastebin.com/xZiV2CDT)
3. `touch Cargo.lock`
4. `emacs Cargo.lock`
5. treemacs will display the PNG icon from treemacs package, not the doom one

:bulb: Note: commenting out lsp-java fixes the issue, but no idea what's happening behind the scenes there.
:bulb: Note-2: commenting out lsp-java with having it downloaded before _does_ exhibit the issue again. It seems the sole presence of lsp-java in `~/.emacs.d/elpa/` triggers the issue.

### Package commit

96edc0ceb864b7d72218e58c8e9272cd96e5712c

### System Information

* Debian 11
* GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.24, cairo version 1.16.0)  of 2021-03-28, modified by Debian

**Comment by taquangtrung** [comment]
@bk138: I'm using Spacemacs and encountered the same issue. Turned out, it was due to treemacs-icon's setting at the line: https://github.com/Alexander-Miller/treemacs/blob/9efcd645c94ba169dac07f0a3296a5b4ca0cd549/src/elisp/treemacs-icons.el#L379

``` emacs-lisp
(treemacs-create-icon :file "vsc/cargo.png"     :extensions ("cargo.toml" "cargo.lock"))
```

FYI, I fixed it by overriding that setting for "cargo.toml"

``` emacs-lisp
  ;; Markup
  (treemacs-create-icon
   :icon (format "  %s%s" (all-the-icons-octicon
                           "code" :v-adjust 0 :face 'all-the-icons-yellow)
                 treemacs-all-the-icons-tab)
   :extensions ("yaml" "json" "toml" "cargo.toml" "cargo.toml")
   :fallback 'same-as-icon)
```
