### ISSUE TITLE
Ample-Zen

### ISSUE THREAD

**Issue by liar666** [doomemacs/themes#727]
### Describe your request

Hi,

I use Ample-Zen since ages in vanilla Emacs and I loved it.

I recently switched to DoomEmacs (because I'm tired of managing my 2000+ lines of config.org and getting half-backed results).
I've `consult`'ed all the Doom themes. Unfortunately, I couldn't find one that suits my needs (org, and many languages : R/Python/Java/Dart/Rust/...):
- I can't use a "light" themes anymore as they burn my eyes
- Most of the Dark themes make org's `#+TITLE` (and other stuff like comments) almost the same color as the background, thus unreadable
- The other ones have nice backgrounds, but too colorful keywords... Thus reading any code in them also burn my eyes.

I'm very bad at lisp/design/colors/etc. Would it be difficult to convert a vanilla Emacs theme like AmpleZen to Doom?

NOTE: I'm publish here as last change in https://github.com/mjwall/ample-zen/issues/4 dates back 9 years :{

### Resources

https://github.com/mjwall/ample-zen

**Comment by jeetelongname** [comment]
You should be able to use that theme in doom, your not limited to just the doom themes, you would install it like any other package and then just the Doom theme variable to that theme. That being said if you can get the colours out of the theme then it should be relatively trivial to convert

**Comment by hlissner** [comment]
> I can't use a "light" themes anymore as they burn my eyes

Amen, brother.

> Most of the Dark themes make org's #+TITLE (and other stuff like comments) almost the same color as the background, thus unreadable

Most of doom's themes have a `doom-NAME-brighter-comments` variable. Like `doom-one` has `doom-one-brighter-comments`. With `(setq doom-one-brighter-comments)`, the comment colors will have more contrast.

> The other ones have nice backgrounds, but too colorful keywords... Thus reading any code in them also burn my eyes.

Emacs themes are easily customizable. Start with any theme as a baseline, then use the `custom-set-faces` macro to tweak whatever you want about them.

If you're using Doom Emacs, use the `custom-set-faces!` macro instead:

```elisp
(custom-set-faces! `(font-lock-comment-face :foreground "red"))
```

More examples of its use with `C-h f custom-set-faces\!` (or `M-x helpful-function RET custom-set-faces\!`).

You can look up faces with `C-h F` (`M-x describe-face`).

> Would it be difficult to convert a vanilla Emacs theme like AmpleZen to Doom?

It'd be a simple matter of copying one of our other themes (I'd recommend doom-one, as it's the most fleshed out), and substituting the colors at the top with AmpleZen.

-----

Anyhow, in the future, please redirect questions like these to [our Discourse](https://discourse.doomemacs.org), as our issue tracker is for bug reports and feature requests.
