### ISSUE TITLE
Silencing Emacs native compiler

### ISSUE THREAD

**Issue by dr-scsi** [doomemacs/themes#729]
### Describe your request

With the latest Emacs 29 master (822350d198), the native compiler issues the following warning:

> In doom-themes-set-faces:
> doom-themes.el:385:2: Warning: docstring has wrong usage of unescaped single quotes (use \= or different quoting)

The following patch should fix the warning:

```
diff --git a/doom-themes.el b/doom-themes.el
index 1e5816c..431c793 100644
--- a/doom-themes.el
+++ b/doom-themes.el
@@ -388,12 +388,12 @@ Variables in EXTRA-VARS override the default ones."
 If THEME is nil, it applies to all themes you load. FACES is a list of Doom
 theme face specs. These is a simplified spec. For example:

-  (doom-themes-set-faces 'user
-    '(default :background red :foreground blue)
-    '(doom-modeline-bar :background (if -modeline-bright modeline-bg highlight))
-    '(doom-modeline-buffer-file :inherit 'mode-line-buffer-id :weight 'bold)
-    '(doom-modeline-buffer-path :inherit 'mode-line-emphasis :weight 'bold)
-    '(doom-modeline-buffer-project-root :foreground green :weight 'bold))"
+  (doom-themes-set-faces \\='user
+    \\='(default :background red :foreground blue)
+    \\='(doom-modeline-bar :background (if -modeline-bright modeline-bg highlight))
+    \\='(doom-modeline-buffer-file :inherit \\='mode-line-buffer-id :weight \\='bold)
+    \\='(doom-modeline-buffer-path :inherit \\='mode-line-emphasis :weight \\='bold)
+    \\='(doom-modeline-buffer-project-root :foreground green :weight \\='bold))"
   (declare (indent defun))
   (apply #'custom-theme-set-faces
          (or theme 'user)
```

### Briefly explain its use-case

1. Install doom-themes
2. Build the latest Emacs master with native-comp enabled
3. Start the latest Emacs and watch it compiling the packages
4. Check the buffer `*Async-native-compile-log*`

**Comment by dr-scsi** [comment]
@hlissner - Ping!  Is there anything I can do to support progress here?  Would a PR help?

**Comment by WillAyd** [comment]
Started getting this warning on startup after upgrading my snap to 29.1 . @dr-scsi maybe worth submitting your patch as a PR? Happy to if you don't have the time

**Comment by iitalics** [comment]
i too just started seeing this warning and would be happy to fix this, but it looks like it doesn't meet the "do not PR" criteria :/ guess we need to wait for a real maintainer to push the fix themselves

**Comment by dr-scsi** [comment]
@WillAyd - Thanks for reminding me about this report.  I sorta forgot/gave up on this `;-)`  Please feel free to submit a PR, maybe that makes it easier for the developer(s) to resolve this issue.  TIA.
