### ISSUE TITLE
Face for dividing vertical line between buffers

### ISSUE THREAD

**Issue by AtomicNess123** [doomemacs/themes#737]
### Describe your request

Not really a request, just could not find how to set a different color for the vertical dividing line between buffers within a window, since the default color is too dark. Thanks!

### Resources

None.

**Comment by hlissner** [comment]
Please use our [Discord](https://doomemacs.org/discord) or [Discourse](https://discourse.doomemacs.org) for support requests. Our issue trackers are for issues and feature requests.

----

As for your question, see https://github.com/doomemacs/themes/issues/369#issuecomment-570747035.
