### ISSUE TITLE
Improve doom-material-dark

### ISSUE THREAD

**Issue by trev-dev** [doomemacs/themes#749]
### Describe your request

Since contributing `doom-material-dark` I have continued to improve the theme on my local machine. I have even "forked" my own theme into a separate theme where much of the development has continued.

I am now checking out Doom again because I feel like "no one does evil like Doom does" and wanted to see how the project has improved. Doom is an *amazing* project and its progress is impressive.

My theme, on the other hand, is seriously lacking in accessibility. Contrast is very poor in some spaces. I am sure there are other issues to be found.

I am making this issue not as a request for anyone to do anything. I am making this issue as a point of accountability for my contribution and as a reminder that there is yet work to be done.

### Briefly explain its use-case

1. My life loves my tomfoolery, thank the gods.

**Comment by christophermadsen** [comment]
Absolutely adore this theme, but it would be nice to have better integration for python files/the Python major mode.
