### ISSUE TITLE
No contrast in org mode code block with doom-monokai-octagon when highlighting code. 

### ISSUE THREAD

**Issue by cddesja** [doomemacs/themes#762]
### Describe your request

For the `doom-monokai-octagon`, which is wonderful by the way, when I select text in an org-mode code block, the highlighted text is the same color as the background so there's no visual indication of what text is being selected. 

I believe the background color of the org code block needs to changed or the selected text color for the theme. 

If you do not want to fulfill request, could you let me know how I can do this locally?

I can upload a screencast if it would help.

### Briefly explain its use-case

1. Install doom-themes
2. Select the doom-monokai-octagon theme
3. Create a code block with the code in it.
4. Highlight the code in the block and notice that the background color is the same color as the highlight color.

**Comment by Walheimat** [comment]
The `doom-monokai-*` themes are really nice but this is a minor annoyance.

I'm not sure if this a valid way for all the themes, but setting the following (in the face overrides) could be one way to solve this.

```elisp
((org-block &override) :background base2)
((org-block-background &override) :background base2)
((org-block-begin-line &override) :background base2)
```

This is what is done in many other themes.
