### ISSUE TITLE
Doom-Pine is missing

### ISSUE THREAD

**Issue by bzwierz** [doomemacs/themes#776]
### Theme(s)

doom-pine

### What were you expecting?

M-x load-theme dom-pine or (setq doom-theme 'doom-pine) should change the theme of Doom.

It works with themes like gruvbox or dracula. 

### What actually happened?

Using lod-theme provided no resaults - doom-pine is simply not there.

Obviously loading it throug config.el didn't work - Doom turns on with black screen. 

### Steps to reproduce

1. M-x load-theme: doom-pine

### Operating system

EndevourOS

### Emacs version

Emacs 28.2

### Installed commit of doom-themes

not sure what it means, sorry!

**Comment by elken** [comment]
Since it was added here https://github.com/doomemacs/themes/commit/b5ff201f4bea4286e9ed015a2043cf2394182232 I'd say your version of doom-themes is outdated. Update the pin to a more recent commit

**Comment by bzwierz** [comment]
I'll check it after work, but just to be clear - I've installed Doom and Emacs literally yesterday. I've run doom upgrade - didn't change anything.

**Comment by elken** [comment]
`doom upgrade` only upgrades the core doom code, not the packages.

I've just checked and the pin is indeed outdated. If you add `(unpin! doom-themes)` to your packages.el and `doom sync -u` you should be good

**Comment by hlissner** [comment]
> doom upgrade only upgrades the core doom code, not the packages.

To clarify this, it upgrades Doom core, any packages whose pins have changed, and any unpinned packages -- but yes, it's been a while since `doom-themes`'s pin has been updated in Doom Emacs.

Since this isn't a doomemacs/themes issue I will close this, but it will be addressed in doomemacs/doomemacs#7092.
