### ISSUE TITLE
doom-rouge-brighter-comments does not change comment colour

### ISSUE THREAD

**Issue by crestofthebeast** [doomemacs/themes#778]
### Theme(s)

doom-rouge

### What were you expecting?

(setq doom-rouge-brighter-comments t) to enable a brighter comment colour

### What actually happened?

i get default(?) comment behaviour/colours

some screenshots. each was taken after changing the (setq doom-rouge-brighter-comments <val>) line, then saving/tangling, hitting `space h r r`, and restarting emacs. 
![image](https://user-images.githubusercontent.com/98293751/225872485-4b4e9823-c0ef-464c-8189-3f7e6ec28df8.png)
![image](https://user-images.githubusercontent.com/98293751/225872864-6e4ecc4d-b8b3-4cfd-bbbb-2a83232e305e.png)

### Steps to reproduce

1. switch to doom-rouge theme
2. setq `doom-rouge-brighter-comments` to `t`
3. save config.org/el
4. restart emacs
5. open a file with comments in it
6. weep, for you wanted brighter comments

### Operating system

macOS Ventura 13.2.1 

### Emacs version

GNU Emacs 28.2 (builh 1, aarch-apple-darwin22.3.0, Carbon Version 169 Appkit 2299.4) of 2023-02-25

### Installed commit of doom-themes

should be `4c239db`

**Comment by hlissner** [comment]
Ah. Seems the theme never uses the variables. I'll get around to fixing this when I can, but PRs are welcome, in the meantime.

**Comment by crestofthebeast** [comment]
will try to give a PR a crack later today, since i've been meaning to learn doom's theme structure.

**Comment by hlissner** [comment]
Do you have any recommendations for what color to use for the brighter comments? I'm playing with `violet`, but I'm not sure it fits the asthetic (or is bright enough):

**base5** (original)
![image](https://github.com/doomemacs/themes/assets/510883/ab87a2b2-3e33-4f7b-91b8-23fe88eff64f)

**violet**
![image](https://github.com/doomemacs/themes/assets/510883/75f6c7f3-db19-4bfd-ba41-0383f877c0bf)
