### ISSUE TITLE
doom-one-comment-bg missing

### ISSUE THREAD

**Issue by aguynamedben** [doomemacs/themes#786]
## `doom-one-comment-bg` was removed

In https://github.com/doomemacs/themes/issues/528 @hlissner explains that in doom-one a combination of `doom-one-brighter-comments t` and `doom-one-comment-bg nil` can be used for brighter comments without also causing the comment background to brighten.

* `doom-one-brighter-comments` still works
* `doom-one-comment-bg` appears to have been [removed](https://github.com/doomemacs/themes/commit/7ce9be332fa6b5f805ee54c47b65e07060aec37c#diff-be4fec6590e4a899a2942852f5fe699cf2cc43fb6191118e6bbe919e91d63f21L19) in 2021 as part of a code cleanup

## Was this intentional?

Was this an intentional removal? I can submit a PR if not.

## Proposals

* **Proposal A:** Don't brighten background when brightening comments
* **Proposal B:** Reintroduce `doom-one-comment-bg`
* **Proposal C:** Do nothing (null hypothesis) 😄

## Opinion + Screenshots

With just `doom-one-brighter-comments` all comments look highlighted, which is weird.

<img width="545" alt="image" src="https://github.com/doomemacs/themes/assets/107841/866cd19f-58b4-4da7-bc15-4a845eb1b274">

I was able to "fix" this by piecing together what `doom-one-comment-bg` used to do:

```elisp
(use-package doom-themes
  :custom
  (doom-one-brighter-comments t)
  :config
  (load-theme 'doom-one t)
  ;; We brightened comments, but don't brighten background
  (custom-set-faces
   `(font-lock-comment-face ((t (:background ,(doom-color 'black)))))))
```

which gives a much cleaner look:

<img width="544" alt="image" src="https://github.com/doomemacs/themes/assets/107841/5a806924-a47d-48c6-8256-b4d6708ac3af">

I'm happy to submit a PR that reintroduces `doom-one-comment-bg` if you think that's a good path forward.

Thanks for providing these epic themes! 🙏 

### Setup

Operating system: macOS Ventura
Emacs version: Emacs 30.0.50 w/ native comp
doom-themes version: doom-themes-20230221.610 from MELPA

**Comment by hlissner** [comment]
Sorry for taking so long to get to this. As of 74fab74 I've restored the setting. Though, some forewarning: I plan to revamp how themes are configured (and written, for that matter) sometime later this year though, since maintaining all these settings separately across the large (and growing) number of themes is becoming a big time sink. That's some time away though.

Anyhow, thanks for bringing this to my attention!
