### ISSUE TITLE
ediff theming doesn't have any colour hightlight

### ISSUE THREAD

**Issue by tien** [doomemacs/themes#792]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

Ediff to have colour highlights for add, remove & modified code

### Current behavior

Everything has a plain grey background

<img width="1512" alt="image" src="https://github.com/doomemacs/doomemacs/assets/19813755/b55acb25-98a3-4b86-b0a2-320c2ffebb66">

### Steps to reproduce

1. Open Emacs
2. Run ediff

### System Information

https://pastebin.com/1T7ENBnY

**Comment by hlissner** [comment]
Was this resolved somehow?

**Comment by tien** [comment]
@hlissner Yeah I asked on Discord & turned out this is the expected behaviour, only selected hunk are highlighted & not all hunks for some reason :l

**Comment by hlissner** [comment]
@tien Ah, yes, that is controlled by the `magit-diff-refine-hunk` variable. To quote its docs (available via `C-h v magit-diff-refine-hunk`):

> Whether to show word-granularity differences within diff hunks.
>
> nil    Never show fine differences.
> t      Show fine differences for the current diff hunk only.
> all  Show fine differences for all displayed diff hunks.

Magit's default for this is `nil`. Doom's default for it is `t` (since it can be expensive if rendered across an entire diff), but setting it to `'all` may be what you're looking for:

```elisp
;; add to ~/.doom.d/config.el
(after! magit
  (setq magit-diff-refine-hunk 'all))
```

**Comment by tien** [comment]
@hlissner Awesome, thank you for the pointer.

Also, one minor thing, right now the before/after change all used the same background colour.

<img width="1274" alt="image" src="https://github.com/doomemacs/themes/assets/19813755/94d9b08b-f8fe-4dcf-bfda-17447ab76710">

Usually, other editors would have different backgrounds to distinguish them:

<img width="1196" alt="image" src="https://github.com/doomemacs/themes/assets/19813755/ac135aef-f778-468e-8e25-5c8fc4162c7e">

Settings this for individual theme would be a pain I guess, but would be nice to have this for at least for `doom one`
