### ISSUE TITLE
error while installing  the badger theme

### ISSUE THREAD

**Issue by seagle0128** [doomemacs/themes#812]
### What were you expecting?

No error

### What actually happened?

Got the error. The backtrace is below:

```elisp
INFO     Scraping files for doom-themes-autoloads.el... 
Error (use-package): Failed to install doom-themes: doom-badger-theme.el:0:0: error: scan-error: (Unbalanced parentheses 1213 9682)
```

### Steps to reproduce

Install the latest version: 20231206.102

### Operating system

any

### Emacs version

Emacs 27, 28, 29

### Installed commit of doom-themes

20231206.102

**Comment by hlissner** [comment]
Should be fixed as of https://github.com/doomemacs/themes/commit/baee64fe5110d077ed40c8fedba2b7dd621156f1. Thanks for letting me know!
