### ISSUE TITLE
"Ansi bright black" color is never readable as a foreground color

### ISSUE THREAD

**Issue by kisaragi-hiu** [doomemacs/themes#833]
### Theme(s)

All themes (base)

### What were you expecting?

The "Ansi bright black" color should always be readable as foreground text.

### What actually happened?

Command line output in ansi-color-bright-black is always actually invisible or almost unreadable on top of the background color, no matter if the theme is dark or light, and no matter the theme in general.

| Konsole (one dark) | Emacs (vterm, doom-one) | Emacs (vterm, doom-one, some text selected) |
|-|-|-|
| ![konsole one dark](https://github.com/user-attachments/assets/b55afff0-c3b7-4aa9-8e74-604d1982c356) | ![emacs vterm doom one](https://github.com/user-attachments/assets/d0a12721-95fa-4a8e-8882-ebac42dd2493) |![text selected via emacs - emacs vterm doom one](https://github.com/user-attachments/assets/e9249003-9f94-46d3-85dc-85604a74cab8) |

(The grayed out suggestion is from [zsh-autosuggestions](https://github.com/zsh-users/zsh-autosuggestions))

If we check the ANSI colors ([via this script](https://stackoverflow.com/a/33206814)), comparing ANSI colors in Konsole and using doom-themes:

| Konsole "black on white" | Konsole "Breeze" | Konsole "One Dark" |
|-|-|-|
| ![konsole black-on-white ansi](https://github.com/user-attachments/assets/86c98801-2e6d-445c-946c-4522a2e61c5a) | ![konsole breeze ansi](https://github.com/user-attachments/assets/784e07bf-71c3-4a56-ac94-75b848d6fca7) | ![konsole one dark ansi](https://github.com/user-attachments/assets/ea0979a8-befa-49c3-943a-6650fe147da7) |

| doom-one-light | doom-one | doom-Iosvkem |
|-|-|-|
| ![ansi emacs doom-one-light](https://github.com/user-attachments/assets/c7b6ecc5-1963-47cd-9488-4cbd42e8ddb2) |![ansi emacs doom-one](https://github.com/user-attachments/assets/dc9530fd-3ae3-441b-be95-999cd479ee1c) | ![ansi emacs doom-Iosvkem](https://github.com/user-attachments/assets/e9673805-3a68-4f80-b220-10863633c11c) |

- In Konsole, ansi-color-white (bottom left) and ansi-color-black (top left) are still black or white, with no invertion being done. Same in emacs (vterm) using colors defined by doom-themes.
- "90" ("bright black") is always readable in Konsole no matter if the background is white or black. **In emacs using doom-themes it's always unreadable no matter the background**.

### Steps to reproduce

1. Use a doom theme
2. Use any command line program that emits text in ansi bright black
   - Like undefined return values in the Node REPL
   - or auto suggestions from fish or zsh-autosuggestions
3. Observe that the text is unreadable in Emacs
4. Run the same command in another terminal
5. Observe that the text is readable in other terminals
6. Run the same command in Emacs but with a non-doom theme, like adwaita
7. Observe that the text is still readable

### Operating system

Arch Linux

### Emacs version

Emacs 29.4

### Installed commit of doom-themes

2c794a09b023bda09d2f36a7be80684f4e416d88

### Other notes

This was originally filed as if it's a problem for ansi black, white, bright black, and bright black in general. Further checks with other programs that display ansi colors showed that it's not the case, and I apologize for the mistake.

**Comment by kisaragi-hiu** [comment]
The builtin leuven (light) and leuven-dark themes seem to take the approach of treating ansi-color-black as foreground.

I initially thought the norm in other terminals is to use white for the first ansi color in a dark theme, but this does not appear to be the case. I need to check more command line programs to see if this is an issue with all four (white/black, bright white/bright black), or if it's just an issue with the "bright" colors.

**Comment by hexaeder** [comment]
The theme `doom-dark+` has a weird definition of the base colors which does not play well with `base6` as bright black. Can this be somehow altered on a per theme basis?

Color codes in `dark+`:
![image](https://github.com/user-attachments/assets/ee663d04-c191-4a3a-8c3d-586ced1a53fb)

**Comment by kisaragi-hiu** [comment]
I assumed that `base1` ~ `base8` are supposed to be ["...a spectrum from bg to fg, where base0 is a starker bg and base8 is a starker fg. For example, if bg is light grey and fg is dark grey, base0 should be white and base8 should be black"](https://github.com/search?q=repo%3Adoomemacs%2Fthemes%20starker%20fg&type=code). That is the case for most themes, but I guess apparently not all. `dark+`'s base6 was added along with the theme itself and I couldn't find an explanation why specifically base6 is blue.

It still fine if `dark+` still wants to use a blue as `base6` while keeping `brightblack` on the gray scale, but I think the theme should then just provide its own definition for `ansi-color-bright-black`. [Many themes already override base theme faces](https://github.com/search?q=repo%3Adoomemacs%2Fthemes%20face%20overrides&type=code) afterall.

**Comment by hexaeder** [comment]
I too was quite surprised by `base6` being this obvious outlier. Thanks for providing the solution, though. I might just PR an `ansi-color-bright-black` definition then!
