### ISSUE TITLE
Papercolor theme status?

### ISSUE THREAD

**Issue by qrilka** [doomemacs/themes#846]
### Describe your request

https://github.com/doomemacs/themes/issues/435 says that papercolor theme is present in the project but I can't find any other trace of it in the repository

### Resources

https://github.com/doomemacs/themes/issues/435
https://github.com/NLKNguyen/papercolor-theme

**Comment by hlissner** [comment]
The request was never fulfilled; it was closed by the requester.

**Comment by qrilka** [comment]
And closed as completed? That's quite confusing :-\
@glepnir could you share some details of that if you remember?

**Comment by hlissner** [comment]
Users generally don't realize that issues can be closed any other way, so that tends to happen, especially if they don't leave a follow up explanation.

In any case, I've "reclosed" #435 to avoid this confusion in the future. I've also unlocked it, so please move the conversation there.
